package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/dinethpiyumantha/eventeo-gql-service/graph/model"
)

// CreateEventListing is the resolver for the createEventListing field.
func (r *mutationResolver) CreateEventListing(ctx context.Context, input model.CreateEventListingInput) (*model.EventListing, error) {
	panic(fmt.Errorf("not implemented: CreateEventListing - createEventListing"))
}

// UpdateEventListing is the resolver for the updateEventListing field.
func (r *mutationResolver) UpdateEventListing(ctx context.Context, id string, input model.UpdateEventListingInput) (*model.EventListing, error) {
	panic(fmt.Errorf("not implemented: UpdateEventListing - updateEventListing"))
}

// DeleteEventListing is the resolver for the deleteEventListing field.
func (r *mutationResolver) DeleteEventListing(ctx context.Context, id string) (*model.DeleteEventResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteEventListing - deleteEventListing"))
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.EventListing, error) {
	panic(fmt.Errorf("not implemented: Events - events"))
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.EventListing, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
