package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/dinethpiyumantha/eventeo-gql-service/database"
	"github.com/dinethpiyumantha/eventeo-gql-service/graph/model"
)

var db = database.Connect()

// CreateEventListing is the resolver for the createEventListing field.
func (r *mutationResolver) CreateEventListing(ctx context.Context, input model.CreateEventListingInput) (*model.EventListing, error) {
	return db.CreateEventListing(input), nil
}

// UpdateEventListing is the resolver for the updateEventListing field.
func (r *mutationResolver) UpdateEventListing(ctx context.Context, id string, input model.UpdateEventListingInput) (*model.EventListing, error) {
	return db.UpdateEventListing(id, input), nil
}

// DeleteEventListing is the resolver for the deleteEventListing field.
func (r *mutationResolver) DeleteEventListing(ctx context.Context, id string) (*model.DeleteEventResponse, error) {
	return db.DeleteEventListing(id), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.EventListing, error) {
	return db.GetEvents(), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.EventListing, error) {
	return db.GetEvent(id), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
