// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEventListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Organizer   string `json:"organizer"`
	URL         string `json:"url"`
}

type DeleteEventResponse struct {
	DeleteEventID string `json:"deleteEventId"`
}

type EventListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Organizer   string `json:"organizer"`
	URL         string `json:"url"`
}

type UpdateEventListingInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	URL         *string `json:"url,omitempty"`
}
